version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: on-failure
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 # Use when running python code outside containers
      - KAFKA_LISTENERS=PLAINTEXT://:9092      
    depends_on:
      - zookeeper
    restart: on-failure
  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    restart: on-failure
  consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - zookeeper
      - kafka
    restart: on-failure

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

